
export const GET_FLOORS = "GET_FLOORS";
export const DELETE_FLOOR = "DELETE_FLOOR";
export const CREATE_FLOOR = "CREATE_FLOOR";
export const UPDATE_FLOOR = "UPDATE_FLOOR";

export const GET_PARKINGS = "GET_PARKINGS";
export const DELETE_PARKING = "DELETE_PARKING";
export const CREATE_PARKING = "CREATE_PARKING";
export const UPDATE_PARKING = "UPDATE_PARKING";


export const GET_PARKING_SPACES = "GET_PARKING_SPACES";
export const DELETE_PARKING_SPACE = "DELETE_PARKING_SPACE";
export const CREATE_PARKING_SPACE = "CREATE_PARKING_SPACE";
export const UPDATE_PARKING_SPACE = "UPDATE_PARKING_SPACE";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const LOGIN_FAILURE = "LOGIN_FAILURE";